<dec f='include/c++/10/bits/exception_ptr.h' l='99' type='void std::__exception_ptr::exception_ptr::exception_ptr(const std::__exception_ptr::exception_ptr &amp; )'/>
<use f='include/c++/10/bits/nested_exception.h' l='70' u='c' c='_ZNKSt16nested_exception14rethrow_nestedEv'/>
<use f='include/c++/10/bits/nested_exception.h' l='76' u='c' c='_ZNKSt16nested_exception10nested_ptrEv'/>
<use f='include/c++/10/future' l='722' u='c' c='_ZNKSt14__basic_future13_M_get_resultEv'/>
<use f='qv2ray/test/catch.hpp' l='13417' u='c' c='_ZN5Catch7SessionC1Ev'/>
