<def f='include/c++/10/future' l='1326' ll='1331' type='void std::promise&lt;void&gt;::set_exception_at_thread_exit(std::__exception_ptr::exception_ptr __p)'/>
